### ISSUE TITLE
projecting an image onto the manifold?

### ISSUE THREAD

**Issue by dribnet** [junyanz/iGAN#2]
Is the model for projecting an image back onto the manifold also packaged with the pre-trained models listed in the README? The code is organized very well and I've been able to use the `Model` class in ``dcgan_theano.py` to sample from the downloaded models, but I'm less clear how to do the inverse mapping `x => z` through the projection model and optimization objective.

**Comment by junyanz** [comment]
Hi Tom,  you are right. It's not included right now. I will release the script for predicting latent vector z from given image x, as well as other training scripts soon (hopefully by Sept 25, Sunday).

**Comment by junyanz** [comment]
I just uploaded a script `iGAN_predict.py' for this. Let me know if it works for you.
