### ISSUE TITLE
The dataset link is not found

### ISSUE THREAD

**Issue by jichunshen** [junyanz/iGAN#21]
The dataset link is not found. (https://people.eecs.berkeley.edu/~junyanz/projects/gvm/datasets/$FILE.zip)
Would you please give a new URL link?

**Comment by junyanz** [comment]
${FILE} is the argument in the bash script. You need to specify the dataset name. See [here](https://github.com/junyanz/iGAN/blob/master/train_dcgan/README.md#datasets) for more details.
