### ISSUE TITLE
Regarding the upcoming  variational autoencoder feature

### ISSUE THREAD

**Issue by kaihuchen** [junyanz/iGAN#4]
This is great stuff!

The README.md mentioned that there is a plan to support variational autoencoder, which I very much look forward to.  My understanding is that the vanilla VAE tends to create blurry images (perhaps due to the disentangled representation that it learns), and I wonder if the planned VAE feature will be based on the vanilla VAE, or something like the *autoencoding beyond pixels*, or *adversarial autoencoders*?

**Comment by junyanz** [comment]
We are looking at different architectures right now such as VAE-GAN or PPGAN. I am busy with a paper deadline right now, and plan to add new architectures by the late Jan or early Feb. If you would like to help add a particular network, send us a pull request.
