### ISSUE TITLE
Motion+Color flow algorithm

### ISSUE THREAD

**Issue by ezamyatin** [junyanz/iGAN#5]
Hi!
Could you explain in detail the Motion+Color flow algorithm?
If there is a corresponding code that would be cool!

**Comment by junyanz** [comment]
It's currently not included in this repo. The high-level idea is to steal the high-res texture from the input image, and paste it to the GAN result. The Motion+Color flow algorithm is a modified version of classic optical flow. It tries to estimate the geometric and color changes between the input GAN result, and the final GAN result. Once we estimate the changes, we can apply it to the input original image, and get a final image.  For more details, please refer to Sec 4.3 in the paper.
